Third milestone feature
DickensJuma/Tic_tac_toe_game pull request #5
Opened 2020-06-30 07:15 UTC by haraphat01

2020-07-07 09:22 UTC, haraphat01 commented
This is our final project on the third milestone project for Tic Tac Toe. The game logic has been made and it's running as it supposed to.

Kindly check for your kind review.

2020-07-07 13:06 UTC, mikenath223 requested changes
### Hi Team 👋

Good job on this @haraphat01  and @DickensJuma  👍

However, let's fix this:
- [ ] Kindly provide a descriptive pull request message, edit this pull request and add a description above it.

- [ ] On the game it's not possible to place a mark at position 1 on the board, please fix this.

Kindly fix these issues and request another review👍
Feel free to contact me on slack(mike) if you need further clarification.

HAPPY CODING👨‍💻

2020-07-08 12:27 UTC, santiago-dev96 requested changes
# Changes required :wrench:

You are doing a great job so far! I almost approve this PR, but there is a little thing that needs to be fixed.

1. When you confirm the prompt for starting a new game the numbers in the board ar displaced, look at the picture below.

![Screenshot from 2020-07-08 08-20-59](https://user-images.githubusercontent.com/43162770/86918440-b6d22500-c0f4-11ea-8199-c4a700079563.png)

I'm sure that if you fix that it is very likely that your PR will be approved next time. Happy coding!

You can find me in slack as **srodrig**.

2020-07-08 12:27 UTC, santiago-rodrig commented on bin/main.rb
> +# rubocop:disable Layout/LineLength, Lint/RedundantCopDisableDirective,Layout/LineLength
Why are you disabling the line length cop? It is a good practice to keen your lines below 120 characters for readability.
```suggestion
```

2020-07-08 12:27 UTC, santiago-rodrig commented on bin/main.rb
> +player1 = gets.chomp.capitalize!
You don't need to use the bang at the end.
```suggestion
player1 = gets.chomp.capitalize
```

2020-07-08 12:27 UTC, santiago-rodrig commented on bin/main.rb
> +  letter_one = gets.chomp.upcase!
```suggestion
  letter_one = gets.chomp.upcase
```

2020-07-08 12:27 UTC, santiago-rodrig commented on bin/main.rb
> +player2 = gets.chomp.capitalize!
```suggestion
player2 = gets.chomp.capitalize
```

2020-07-08 12:27 UTC, santiago-rodrig commented on bin/main.rb
> +while [player1].include?(player2)
```suggestion
while player1 == player2
```

2020-07-08 12:27 UTC, santiago-rodrig commented on bin/main.rb
> +  player2 = gets.chomp.capitalize!
```suggestion
  player2 = gets.chomp.capitalize
```

2020-07-08 13:05 UTC, haraphat01 commented
Thanks for your review.

We've worked on the requested changes. The board is no more displacing the board numbers while on the verge to restart the game and also the bang method has been removed.

2020-07-08 18:40 UTC, wathigo approved these changes
### Approved :heavy_check_mark: 
You have done an amazing job on this project!
I enjoyed playing the game.

**You may proceed to the next project.**

**Good luck :four_leaf_clover: 
Simon Wathigo**

2020-07-09 13:00 UTC, merged